apps/crud_alumnos/urls.py
from django.conf.urls import url
from apps.crud_alumnos.views import alumnosCreate, alumnosList, alumnosDelete, alumnosUpdate, alumnoShow, search, \
    carrerasCreate, carrrerasList, carrerasUpdate, carrerasDelete, carrerasShow, search_c

urlpatterns = [
    url(r'^nuevo/', alumnosCreate.as_view(), name='alumno_crear'),
    url(r'^listar/', alumnosList.as_view(), name='alumnos_listar'),
    url(r'^eliminar/(?P<pk>\d+)/$', alumnosDelete.as_view(), name='alumno_eliminar'),
    url(r'^modificar/(?P<pk>\d+)/$', alumnosUpdate.as_view(), name='alumno_editar'),
    url(r'^mostrar/(?P<pk>\d+)/$', alumnoShow.as_view(), name='alumno_mostrar'),
    url(r'^buscar/$', search, name='alumno_buscar'),
    #aqui inicia el crud de carreras
    url(r'^nueva/', carrerasCreate.as_view(), name='carrera_crea'),
    url(r'^lista/', carrrerasList.as_view(), name='carrera_lista'),
    url(r'^edita/(?P<pk>\d+)/$', carrerasUpdate.as_view(), name='carrera_edita'),
    url(r'^borrar/(?P<pk>\d+)/$', carrerasDelete.as_view(), name='carrera_borrar'),
    url(r'^ver/(?P<pk>\d+)/$', carrerasShow.as_view(), name='carrera_ver'),
    url(r'^busca/$', search_c, name='carrera_busca')
]

miprojecto/urls.py
from django.conf.urls import url, include

urlpatterns = [
url(r'^alumnos/', include(('apps.crud_alumnos.urls', 'apps'), namespace='alumnos')),
url(r'^carreras/', include(('apps.crud_alumnos.urls', 'apps'), namespace='carreras'))
]

apps/crud_alumnos/models.py
from django.db import models

# Create your models here.


class carreras(models.Model):
    id = models.IntegerField(primary_key=True)
    nombre = models.CharField(max_length=100)

# aqui se crea el metodo __str__ para mostrar las carreras en el formulario de alumnos

    def __str__(self):
        return '{}'.format(self.nombre)


class alumnos(models.Model):
    nocontrol = models.BigIntegerField(primary_key=True)
    nombre = models.CharField(max_length=50)
    apellido_paterno = models.CharField(max_length=50)
    apellido_materno = models.CharField(max_length=50)
    fecha_nacimiento = models.DateField()
    carreras = models.ForeignKey(carreras, null=True, blank=True, on_delete=models.CASCADE)

"""
despues se ejecuta el comando para realizar la migración del modelo a la base de datos

 python manage.py makemigrations
 python manage.py migrate

se insertan datos a la base de datos con python manage.py shell

 from apps.crud_alumnos.models import carreras

 c = carreras(id = 1, nombre = 'ingenieria en informatica')
 c.save()
"""

apps/crud_profesores/models.py
from django.db import models

# Create your models here.

apps/crud_alumnos/forms.py
# aqui se Crea el formulario

from django import forms
from apps.crud_alumnos.models import alumnos, carreras


class alumnosForm(forms.ModelForm):
    class Meta:
        model = alumnos
        fields = [
            'nocontrol',
            'nombre',
            'apellido_paterno',
            'apellido_materno',
            'fecha_nacimiento',
            'carreras'
        ]
        labels = {
            'nocontrol': 'Numero de Control',
            'nombre' : 'Nombres',
            'apellido_paterno': 'Apellido Paterno',
            'apellido_materno': 'Apellido Materno',
            'fecha_nacimiento': 'Fecha de Nacimiento',
            'carreras': 'Carrera'
        }

        widgets = {
            'nocontrol': forms.TextInput(attrs={'class':'form-control'}),
            'nombre': forms.TextInput(attrs={'class':'form-control'}),
            'apellido_paterno': forms.TextInput(attrs={'class':'form-control'}),
            'apellido_materno': forms.TextInput(attrs={'class':'form-control'}),
            'fecha_nacimiento': forms.TextInput(attrs={'class':'datepicker'}),
            'carreras': forms.Select(attrs={'class':'form-control'}),
        }


class carrerasForm(forms.ModelForm):
    class Meta:
        model = carreras
        fields = [
            'id',
            'nombre'
        ]
        labels = {
            'id':'Clave de Carrera',
            'nombre':'Nombre de la Carrera'
        }
        widgets = {
            'id':forms.TextInput(attrs={'class':'form-control'}),
            'nombre':forms.TextInput(attrs={'class':'form-control'})
        }

apps/crud_alumnos/views.py
# Paso 11. Crear una vista
# Paso 12. Agregar a la carpeta static los archivos css y js del framework
#          materialize
# Paso 13. Crear las carpetas 'base' y 'crudalumnos' en la carpeta templates
# Paso 14. Crear los archivos base.html y alumnos_form.html y guardarlos en
#          las carpetas 'base' y 'crudalumnos' respectivamente

from django.shortcuts import render
from django.views.generic import CreateView, ListView, DeleteView, UpdateView, DetailView
from apps.crud_alumnos.models import alumnos, carreras
from apps.crud_alumnos.forms import alumnosForm, carrerasForm
from apps.crud_alumnos.filters import alumnosFilter, carrerasFilter
from django.urls import reverse_lazy
# Create your views here.


class alumnosCreate(CreateView):
    model = alumnos
    form_class = alumnosForm
    template_name = 'crudalumnos/alumnos_form.html'
    success_url = reverse_lazy('alumnos:alumnos_listar')


class alumnosList(ListView):
    queryset = alumnos.objects.order_by('nocontrol')
    template_name = 'crudalumnos/alumnos_list.html'
    paginate_by = 1


class alumnosUpdate(UpdateView):
    model = alumnos
    form_class = alumnosForm
    template_name = 'crudalumnos/alumnos_form.html'
    success_url = reverse_lazy('alumnos:alumnos_listar')


class alumnosDelete(DeleteView):
    model = alumnos
    template_name = 'crudalumnos/alumnos_delete.html'
    success_url = reverse_lazy('alumnos:alumnos_listar')


class alumnoShow(DetailView):
    model = alumnos
    template_name = 'crudalumnos/alumno_show.html'
# buscar o filtrar
# Para agregar la vista de búsqueda, se instala primero
# pip install django-filters
def search(request):
    alumnos_list = alumnos.objects.all()
    alumnos_filter = alumnosFilter(request.GET, queryset=alumnos_list)
    return render(request, 'crudalumnos/alumnos_list_filter.html', {'filter': alumnos_filter})
#aqui inicia el crud de carrreras

class carrerasCreate(CreateView):
    model = carreras
    form_class = carrerasForm
    template_name = 'crudalumnos/carreras_form.html'
    success_url = reverse_lazy ('carreras:carrera_lista')


class carrrerasList(ListView):
    queryset = carreras.objects.order_by('id')
    template_name = 'crudalumnos/carreras_list.html'
    paginate_by = 10


class carrerasUpdate(UpdateView):
    model = carreras
    form_class = carrerasForm
    template_name = 'crudalumnos/carreras_form.html'
    success_url = reverse_lazy('carreras:carrera_lista')


class carrerasDelete(DeleteView):
    model = carreras
    template_name = 'crudalumnos/carreras_delete.html'
    success_url = reverse_lazy('carreras:carrera_lista')


class carrerasShow(DetailView):
    model = carreras
    template_name = 'crudalumnos/carrera_show.html'

def search_c(request):
    carreras_list = carreras.objects.all()
    carreras_filter = carrerasFilter(request.GET, queryset=carreras_list)
    return render(request, 'crudalumnos/carreras_list_filter.html', {'filter': carreras_filter})

apps/crud_profesores/views.py
from django.shortcuts import render

# Create your views here.

templates/base/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="es">
<head>
	<meta charset="UTF-8">

	{% block extrastatic %}
	{% endblock %}

	<link rel="stylesheet" href="{% static 'css/materialize.min.css' %}">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
	<title>{% block title %}Formulario {% endblock %}</title>
</head>
<body>
<div class="container">
    {% block navbar %}
        <div class="row">
            <div class="col s12 m12 l12">
                <!-- Dropdown Structure -->
                <ul id="dropdown1" class="dropdown-content">
                    <li><a href="{% url 'alumnos:alumno_crear' %}">Registrar</a></li>
                    <li><a href="{% url 'alumnos:alumnos_listar' %}">Listar</a></li>
                    <li><a href="{% url 'alumnos:alumno_buscar' %}">Buscar/Filtrar</a></li>
                </ul>
                <nav class="deep-purple darken-1">
                    <div class="nav-wrapper">
                        <a href="#" class="brand-logo">Inicio</a>
                        <ul class="right hide-on-med-and-down">

                            <li><a class="dropdown-trigger" href="#" data-target="dropdown1">Alumnos<i class="material-icons right">arrow_drop_down</i></a></li>
                            <li><a href="http://www.leonet.mx/" onclick="pageTracker._link(this.href); return false;">Conoce al Desarrollador</a></li>
                            <li><a href="#">Salir</a></li>
                            <!-- Dropdown Trigger -->
                        </ul>
                    </div>
                </nav>
           	</div>
        </div>

	{% endblock %}


	{% block content %}
	<h4>	Bloque de contenido		</h4>
	{% endblock %}


	{% block footer %}
	{% endblock%}
<div class="row">
    <div class="col s12 m12 l12">
        <footer class="page-footer deep-purple accent-2">
            <div class="footer-copyright">
                &copy; 2018 Ismael Soto Santamaria
            </div>
        </footer>
    </div>
</div>
</div>

	<script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
	<script src="{% static 'js/materialize.min.js' %}"></script>
    <script>
        $(document).ready(function() {
            $(".dropdown-trigger").dropdown();
            $('select').formSelect();
            $('.collapsible').collapsible();
            $('.datepicker').datepicker({
                format: 'yyyy-mm-dd'
            });
            $('.button-collapse').sideNav({});
            $('.materialboxed').materialbox();
            $(".button-collapse").sideNav();
            $('.scrollspy').scrollSpy();
            $('.modal').modal();
        });
    </script>
	{% block extrajs %}
	{% endblock %}

</body>
</html>

templates/base/bases.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="es">
<head>
	<meta charset="UTF-8">

	{% block extrastatic %}
	{% endblock %}

	<link rel="stylesheet" href="{% static 'css/materialize.min.css' %}">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
	<title>{% block title %}Formulario {% endblock %}</title>
</head>
<body>
<div class="container">
    {% block navbar %}
        <div class="row">
            <div class="col s12 m12 l12">
                <!-- Dropdown Structure -->
                <ul id="dropdown1" class="dropdown-content">
                    <li><a href="{% url 'carreras:carrera_crea' %}">Registrar</a></li>
                    <li><a href="{% url 'carreras:carrera_lista' %}">Listar</a></li>
                    <li><a href="{% url 'carreras:carrera_busca' %}">Buscar/Filtrar</a></li>
                </ul>
                <nav class="deep-purple darken-1">
                    <div class="nav-wrapper">
                        <a href="#" class="brand-logo">Inicio</a>
                        <ul class="right hide-on-med-and-down">

                            <li><a class="dropdown-trigger" href="#" data-target="dropdown1">Carreras <i class="material-icons right">arrow_drop_down</i></a></li>
                            <li><a href="http://www.leonet.mx/" onclick="pageTracker._link(this.href); return false;">Conoce al Desarrollador</a></li>
                            <li><a href="#">Salir</a></li>
                            <!-- Dropdown Trigger -->
                        </ul>
                    </div>
                </nav>
           	</div>
        </div>

	{% endblock %}


	{% block content %}
	<h4>	Bloque de contenido		</h4>
	{% endblock %}


	{% block footer %}
	{% endblock%}
<div class="row">
    <div class="col s12 m12 l12">
        <footer class="page-footer deep-purple accent-1">
            <div class="footer-copyright">
                &copy; 2018 Ismael Soto Santamaria
            </div>
        </footer>
    </div>
</div>
</div>

	<script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
	<script src="{% static 'js/materialize.min.js' %}"></script>
    <script>
        $(document).ready(function() {
            $(".dropdown-trigger").dropdown();
            $('select').formSelect();
            $('.collapsible').collapsible();
            $('.button-collapse').sideNav({});
            $('.materialboxed').materialbox();
            $(".button-collapse").sideNav();
            $('.scrollspy').scrollSpy();
            $('.modal').modal();
        });
    </script>
	{% block extrajs %}
	{% endblock %}

</body>
</html>

templates/crudalumnos/alumno_show.html
{% extends 'base/base.html' %}

{% block content %}
<div class="row">
    <div class="col s12 m12 l12">
        <p><strong>N&uacute;mero de control: </strong>{{ object.nocontrol }} </p>
        <p><strong>Nombre: </strong>{{ object.nombre }} </p>
        <p><strong>Apellido Paterno: </strong>{{ object.apellido_paterno }} </p>
        <p><strong>Apellido Materno: </strong>{{ object.apellido_materno }} </p>
        <p><strong>Fecha de Nacimiento: </strong>{{ object.fecha_nacimiento }} </p>
        <p><strong>Carrera: </strong>{{ object.carreras }} </p>

        <a class= "btn" href="{% url 'alumnos:alumnos_listar' %}">Ok</a>
        <a class= "btn blue" href="{% url 'alumnos:alumno_editar' object.nocontrol%}"><i class="material-icons">create</i></a>
        <a class="btn red" href="{% url 'alumnos:alumno_eliminar' object.nocontrol %}"><i class="material-icons">delete</i></a>
    </div>
</div>


{% endblock %}

templates/crudalumnos/alumnos_delete.html
{% extends 'base/base.html' %}

{% block content %}
    <div class="row">
        <div class="col s12 m12 l12">
            <form method="post">
                {% csrf_token %}
                <h3>¿Desea eliminar el registro de {{ object.nombre }}?</h3>
                <button class="btn btn-danger" type="submit">Sí, eliminar</button>
                <a class= "btn btn-default" href="{% url 'alumnos:alumnos_listar' %}">Cancelar</a>
            </form>
        </div>
    </div>
{% endblock %}

templates/crudalumnos/alumnos_form.html
{% extends 'base/base.html' %}

{% block content %}
    <div class="row">
        <div class="col s12 m12 l12">
            <form method="post">
	            {% csrf_token %}
	            {{ form.as_p }}
	            <button class="btn blue" type="submit">Guardar<i class="material-icons right">send</i></button>
	            <a class= "btn red" href="{% url 'alumnos:alumnos_listar' %}">Cancelar<i class="material-icons right">cancel</i></a>
            </form>
        </div>
    </div>
{% endblock %}

templates/crudalumnos/alumnos_list.html
{% extends 'base/base.html' %}

{% block content %}

     {% if object_list %}
    {% for alumnos in object_list %}

<div class="row">
    <div class="col s12 m7">
        <div class="card">
            <div class="card blue lighten-5">
                <div class="card-content black-text">
                    <span class="card-title">{{ alumnos.nocontrol }}</span>
                    <p>Nombre Completo: {{alumnos.nombre }} {{ alumnos.apellido_paterno }} {{ alumnos.apellido_materno}}</p>
                    <p>Fecha de Nacimiento: {{ alumnos.fecha_nacimiento }}</p>
                    <p>Carrera: {{ alumnos.carreras }}</p>
        </div>
        <div class="card-action">
            <a class="btn green" href="{% url 'alumnos:alumno_mostrar' alumnos.nocontrol %}"><i class="material-icons">zoom_in</i> </a>
            <a class="btn blue" href="{% url 'alumnos:alumno_editar' alumnos.nocontrol %}"><i class="material-icons">create</i></a>
            <a class="btn red" href="{% url 'alumnos:alumno_eliminar' alumnos.nocontrol %}"><i class="material-icons">delete</i></a>
        </div>
      </div>
    </div>
  </div>
        {% endfor %}
                {% else %}
		            <h1>No hay registros de alumnos</h1>
		        {% endif %}

    <div class="row">
        <div class="col s12 m12 l12">
            <ul class="pagination center">
	            <li>
		        {% if page_obj.has_previous %}
       	            <a class="btn blue" href="?page={{ page_obj.previous_page_number }}"><i class="material-icons">navigate_before</i></a>
		        {% endif %}
                </li>
	            <li>
		        {% if page_obj.has_next %}
                    <a class="btn red" href="?page={{ page_obj.next_page_number }}"><i class="material-icons">navigate_next</i></a>
    	        {% endif %}
                </li>
            </ul>
        </div>
    </div>
</div>>
{% endblock%}

templates/crudalumnos/alumnos_list_filter.html
{% extends 'base/base.html' %}

{% block content %}
<div class="row">
    <div class="col s12 m12 l12">
        <h4>Filtrar por:</h4>
        <form method="get">
            <p>
            <div class="col s4 m4 l4">
            No. Control: &nbsp{{ filter.form.nocontrol }} &nbsp
            </div>
            <div class="col s4 m4 l4">
                Nombres: &nbsp {{ filter.form.nombre }} &nbsp
            </div>
            <div class="col s4 m4 l4">
                Carreras: &nbsp{{ filter.form.carreras }} &nbsp;&nbsp;
                <button class="btn blue" type="submit">Filtrar</button>
            </div>
            </p>
        </form>
        <table class="striped">
	        <thead>
		        <tr>
			        <td>No. Control</td>
			        <td>Nombres</td>
			        <td>Apellido Paterno</td>
                    <td>Apellido Materno</td>
			        <td>Fecha de Nacimiento</td>
                    <td>Carrera</td>
                </tr>
            </thead>
            <tbody>
            {% if filter.qs %}
                {% for alumnos in filter.qs %}
		        <tr>
			        <td>{{ alumnos.nocontrol }}</td>
			        <td>{{ alumnos.nombre }}</td>
			        <td>{{ alumnos.apellido_paterno }}</td>
			        <td>{{ alumnos.apellido_materno }}</td>
			        <td>{{ alumnos.fecha_nacimiento }}</td>
			        <td>{{ alumnos.carreras }}</td>
			        <td>
				        <a class="btn" href="{% url 'alumnos:alumno_mostrar' alumnos.nocontrol %}"><i class="material-icons">zoom_in</i></a>
                        <a class="btn blue" href="{% url 'alumnos:alumno_editar' alumnos.nocontrol %}"><i class="material-icons">create</i></a>
                        <a class="btn red" href="{% url 'alumnos:alumno_eliminar' alumnos.nocontrol %}"><i class="material-icons">delete</i></a>
			        </td>
		        </tr>
		        {% endfor %}

                {% else %}
		            <h1>No hay registros de alumnos</h1>
		        {% endif %}
            </tbody>
        </table>
    </div>
</div>
    <div class="row">
        <div class="col s12 m12 l12">
            <ul class="pagination center">
	            <li>
		        {% if page_obj.has_previous %}
       	            <a class="btn blue" href="?page={{ page_obj.previous_page_number }}"><i class="material-icons">navigate_before</i></a>
		        {% endif %}
                </li>
	            <li>
		        {% if page_obj.has_next %}
     	            <a class="btn red" href="?page={{ page_obj.next_page_number }}"><i class="material-icons">navigate_next</i></a>
    	        {% endif %}
                </li>
            </ul>
        </div>
    </div>

{% endblock%}

templates/crudalumnos/carrera_show.html
{% extends 'base/bases.html' %}

{% block content %}
<div class="row">
    <div class="col s12 m12 l12">
        <p><strong>N&uacute;mero de control: </strong>{{ object.id }} </p>
        <p><strong>Nombre: </strong>{{ object.nombre }} </p>
        <a class= "btn" href="{% url 'carreras:carrera_lista' %}">Ok</a>
        <a class= "btn blue" href="{% url 'carreras:carrera_edita' object.id%}"><i class="material-icons">create</i></a>
        <a class="btn red" href="{% url 'carreras:carrera_borrar' object.id %}"><i class="material-icons">delete</i></a>
    </div>
</div>


{% endblock %}

templates/crudalumnos/carreras_delete.html
{% extends 'base/bases.html' %}

{% block content %}
    <div class="row">
        <div class="col s12 m12 l12">
            <form method="post">
                {% csrf_token %}
                <h3>¿Desea eliminar el registro de {{ object.nombre }}?</h3>
                <button class="btn btn-danger" type="submit">Sí, eliminar</button>
                <a class= "btn btn-default" href="{% url 'carreras:carrera_lista' %}">Cancelar</a>
            </form>
        </div>
    </div>
{% endblock %}

templates/crudalumnos/carreras_form.html
{% extends 'base/bases.html' %}

{% block content %}
    <div class="row">
        <div class="col s12 m12 l12">
            <form method="post">
	            {% csrf_token %}
	            {{ form.as_p }}
	            <button class="btn blue" type="submit">Guardar<i class="material-icons right">send</i></button>
	            <a class= "btn red" href="{% url 'carreras:carrera_lista' %}">Cancelar<i class="material-icons right">cancel</i></a>
            </form>
        </div>
    </div>
{% endblock %}

templates/crudalumnos/carreras_list.html
{% extends 'base/bases.html' %}

{% block content %}
<div class="row">
    <div class="col s12 m12 l12">
        <table class="striped">
	        <thead>
		        <tr>
			        <td>ID Carrera</td>
			        <td>Nombre</td>
                </tr>
            </thead>
            <tbody>
		        {% if object_list %}
		        {% for carreras in object_list %}
		        <tr>
			        <td>{{ carreras.id }}</td>
			        <td>{{ carreras.nombre }}</td>
			        <td>
				        <a class="btn" href="{% url 'carreras:carrera_ver' carreras.id %}"><i class="material-icons">zoom_in</i></a>
                        <a class="btn blue" href="{% url 'carreras:carrera_edita' carreras.id %}"><i class="material-icons">create</i></a>
                        <a class="btn red" href="{% url 'carreras:carrera_borrar' carreras.id %}"><i class="material-icons">delete</i></a>
			        </td>
		        </tr>
		        {% endfor %}

                {% else %}
		            <h1>No hay registros de carreras</h1>
		        {% endif %}
            </tbody>
        </table>
    </div>
</div>

    <div class="row">
        <div class="col s12 m12 l12">
            <ul class="pagination center">
	            <li>
		        {% if page_obj.has_previous %}
       	            <a class="btn blue" href="?page={{ page_obj.previous_page_number }}"><i class="material-icons">navigate_before</i></a>
		        {% endif %}
                </li>
	            <li>
		        {% if page_obj.has_next %}
                    <a class="btn red" href="?page={{ page_obj.next_page_number }}"><i class="material-icons">navigate_next</i></a>
    	        {% endif %}
                </li>
            </ul>
        </div>
    </div>
{% endblock%}

templates/crudalumnos/carreras_list_filter.html
{% extends 'base/bases.html' %}

{% block content %}
<div class="row">
    <div class="col s12 m12 l12">
        <h4>Filtrar por:</h4>
        <form method="get">
            <p>
            <div class="col s4 m4 l4">
                Nombre de la carrera: &nbsp {{ filter.form.nombre }} &nbsp
                <button class="btn blue" type="submit">Filtrar</button>
            </div>
            </p>
        </form>
        <table class="striped">
	        <thead>
		        <tr>
			        <td>Clave de la Carrera:</td>
			        <td>Nombre de la Carrera:</td>
                </tr>
            </thead>
            <tbody>
            {% if filter.qs %}
                {% for carreras in filter.qs %}
		        <tr>
			        <td>{{ carreras.id }}</td>
			        <td>{{ carreras.nombre }}</td>
			        <td>
				        <a class="btn" href="{% url 'carreras:carrera_ver' carreras.id %}"><i class="material-icons">zoom_in</i></a>
                        <a class="btn blue" href="{% url 'carreras:carrera_edita' carreras.id %}"><i class="material-icons">create</i></a>
                        <a class="btn red" href="{% url 'carreras:carrera_borrar' carreras.id %}"><i class="material-icons">delete</i></a>
			        </td>
		        </tr>
		        {% endfor %}

                {% else %}
		            <h3>No hay registro de la Carrera</h3>
		        {% endif %}
            </tbody>
        </table>
    </div>
</div>
    <div class="row">
        <div class="col s12 m12 l12">
            <ul class="pagination center">
	            <li>
		        {% if page_obj.has_previous %}
       	            <a class="btn blue" href="?page={{ page_obj.previous_page_number }}"><i class="material-icons">navigate_before</i></a>
		        {% endif %}
                </li>
	            <li>
		        {% if page_obj.has_next %}
     	            <a class="btn red" href="?page={{ page_obj.next_page_number }}"><i class="material-icons">navigate_next</i></a>
    	        {% endif %}
                </li>
            </ul>
        </div>
    </div>

{% endblock%}